package com.example.planningpattern.model;

import java.util.List;

/**
 * Represents a task plan generated by the planner
 */
public class TaskPlan {
    private final String goal;
    private final List<String> steps;
    private boolean completed;

    public TaskPlan(String goal, List<String> steps) {
        this.goal = goal;
        this.steps = steps;
        this.completed = false;
    }

    public String getGoal() {
        return goal;
    }

    public List<String> getSteps() {
        return steps;
    }

    public boolean isCompleted() {
        return completed;
    }

    public void setCompleted(boolean completed) {
        this.completed = completed;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Task Plan for: ").append(goal).append("\n");
        sb.append("Steps:\n");
        for (int i = 0; i < steps.size(); i++) {
            sb.append(i + 1).append(". ").append(steps.get(i)).append("\n");
        }
        sb.append("Status: ").append(completed ? "Completed" : "Not Completed");
        return sb.toString();
    }
}
